### ISSUE TITLE
Why i cannot inject Callable if functional style instead of class?

### ISSUE THREAD

**Issue by vitalij23** [ivankorobkov/python-inject#41]
.

**Comment by vitalij23** [comment]
Why I cannot inject Callable in functional style instead of class?

**Comment by vitalij23** [comment]
# config
def my_config(binder):
    binder.bind_to_provider('dbfunc', lambda: realdbfunc)
# usage
import inject
db: callable = inject.attr('dbfunc')
db()
# not working:
@inject.autoparams('dbfunc')
def a(dbfunc:callable):
  dbfunc()

**Comment by ivankorobkov** [comment]
Hi,

`@inject.autoparams` injection works on types as in `dbfunc:callable`. However, you bind your `realdbfunc` to a string `dbfunc`. You may try to switch it to:
```python
binder.bind_to_provider(callable, lambda: ...)
```
But It don't think it will work either because keys must be hashable, and `callable` as far as I remember is not.

So, instead of `autoparams` use `params`:
```python
binder.bind_to_provider('dbfunc', lambda: ...) # 'dbfunc' is a key.

@inject.params(dbfunc='dbfunc') # param name to a binder key.
def a(dbfunc):
  pass
```
