### ISSUE TITLE
Support for parallel test execution

### ISSUE THREAD

**Issue by languitar** [ivankorobkov/python-inject#74]
Is there any support or plan for enabling parallel test execution with inject?

**Comment by ivankorobkov** [comment]
Hi!

What do you mean by _parallel test execution with inject_? Can you give an example?

**Comment by languitar** [comment]
For instance for pyest, [pytest-parallel](https://pypi.org/project/pytest-parallel/) provides a way to execute tests in multiple processes and also threads. For multi-threaded testing, the global nature of the inject instance is currently a hindrance, because reconfiguring the injector for one test might affect another test currently running in another parallel thread.

**Comment by ivankorobkov** [comment]
The `inject` API is built on top of a global injector singleton. Getting rid of this singleton requires rewriting the API and dramatically complicates usage and thread-safety.

However, you still can use  pytest-parallel to run tests in parallel:
* Run tests in subprocesses, not threads.
* Initialise the injector in each subprocess, so that each subprocess has its own injector instance.

**Comment by languitar** [comment]
Ok, I know about xdist and that option. This was more a question of whether something like that is generally in scope or not.

Btw. do you have a preferred way of how to integrate inject with pytest fixtures?

**Comment by ivankorobkov** [comment]
> Btw. do you have a preferred way of how to integrate inject with pytest fixtures?

Well, I've never used pytest.

**Comment by languitar** [comment]
Ok. Thanks for the help in any case!
